# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QTableWidget, QTableWidgetItem, QHeaderView, QAbstractItemView, QMessageBox,QWidget
from PyQt6.QtGui import QFont,QIcon
from PyQt6.QtCore import Qt, QSize, QRect, QPoint, QEvent
import math

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(592, 344)
        # disable resizeable
        Dialog.setFixedSize(Dialog.width(), Dialog.height())
        Dialog.setWindowIcon(QIcon('logo/logo.jpeg'))
        Dialog.setFixedSize(592, 344)
        # set minixzed
       
        
        self.frame_display = QtWidgets.QFrame(parent=Dialog)
        self.frame_display.setGeometry(QtCore.QRect(30, 0, 551, 71))
        self.frame_display.setStyleSheet("QFrame{\n"
"background-color:blue;\n"
"color:white;\n"
"}")
        self.frame_display.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame_display.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame_display.setLineWidth(10)
        self.frame_display.setObjectName("frame_display")
        self.label_display = QtWidgets.QLabel(parent=self.frame_display)
        self.label_display.setGeometry(QtCore.QRect(16, 19, 521, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_display.setFont(QFont("sanserif",25))
        self.label_display.setObjectName("label_display")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(20, 79, 561, 311))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 101, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.num7_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.num7_btn.setFont(font)
        self.num7_btn.setObjectName("num7_btn")
        self.verticalLayout.addWidget(self.num7_btn)
        # clicked=lambda:self.press_it("7")
        
        
        self.num4_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
       
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.num4_btn.setFont(font)
        self.num4_btn.setObjectName("num4_btn")
        self.verticalLayout.addWidget(self.num4_btn)
        self.num1_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.num1_btn.setFont(font)
        self.num1_btn.setObjectName("num1_btn")
        self.verticalLayout.addWidget(self.num1_btn)
        self.num00_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.num00_btn.setFont(font)
        self.num00_btn.setObjectName("num00_btn")
        self.verticalLayout.addWidget(self.num00_btn)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(120, 0, 101, 261))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.num8_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.num8_btn.setFont(font)
        self.num8_btn.setObjectName("num8_btn")
        self.verticalLayout_2.addWidget(self.num8_btn)
        self.num5_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.num5_btn.setFont(font)
        self.num5_btn.setObjectName("num5_btn")
        self.verticalLayout_2.addWidget(self.num5_btn)
        self.num2_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.num2_btn.setFont(font)
        self.num2_btn.setObjectName("num2_btn")
        self.verticalLayout_2.addWidget(self.num2_btn)
        self.num000_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.num000_btn.setFont(font)
        self.num000_btn.setObjectName("num000_btn")
        self.verticalLayout_2.addWidget(self.num000_btn)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=self.frame)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(230, 0, 101, 261))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.num9_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.num9_btn.setFont(font)
        self.num9_btn.setObjectName("num9_btn")
        self.verticalLayout_3.addWidget(self.num9_btn)
        self.num6_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.num6_btn.setFont(font)
        self.num6_btn.setObjectName("num6_btn")
        self.verticalLayout_3.addWidget(self.num6_btn)
        self.num3_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.num3_btn.setFont(font)
        self.num3_btn.setObjectName("num3_btn")
        self.verticalLayout_3.addWidget(self.num3_btn)
        self.dot_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.dot_btn.setFont(font)
        self.dot_btn.setObjectName("dot_btn")
        self.verticalLayout_3.addWidget(self.dot_btn)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(parent=self.frame)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(340, 0, 106, 261))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.percent_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.percent_btn.setFont(font)
        self.percent_btn.setObjectName("percent_btn")
        self.verticalLayout_4.addWidget(self.percent_btn)
        self.multiply_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.multiply_btn.setFont(font)
        self.multiply_btn.setObjectName("multiply_btn")
        self.verticalLayout_4.addWidget(self.multiply_btn)
        self.plus_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.plus_btn.setFont(font)
        self.plus_btn.setObjectName("plus_btn")
        self.verticalLayout_4.addWidget(self.plus_btn)
        self.minus_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.minus_btn.setFont(font)
        self.minus_btn.setObjectName("minus_btn")
        self.verticalLayout_4.addWidget(self.minus_btn)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(parent=self.frame)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(460, 0, 106, 261))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.division_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.division_btn.setFont(font)
        self.division_btn.setObjectName("division_btn")
        self.verticalLayout_5.addWidget(self.division_btn)
        self.delete_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.delete_btn.setFont(font)
        self.delete_btn.setStyleSheet("QPushButton{\n"
"background-color:red;\n"
"color:white;\n"
"}")
        self.delete_btn.setObjectName("delete_btn")
        self.verticalLayout_5.addWidget(self.delete_btn)
        self.clear_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.clear_btn.setFont(font)
        self.clear_btn.setObjectName("clear_btn")
        self.verticalLayout_5.addWidget(self.clear_btn)
        self.equls_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.equls_btn.setFont(font)
        self.equls_btn.setObjectName("equls_btn")
        self.verticalLayout_5.addWidget(self.equls_btn)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        
        self.plus_btn.clicked.connect(self.plus_btn_get)
        self.minus_btn.clicked.connect(self.minus_btn_get)
        self.division_btn.clicked.connect(self.division_btn_get)
        self.multiply_btn.clicked.connect(self.multiply_btn_get)
        self.delete_btn.clicked.connect(self.delete_btn_get)
        self.clear_btn.clicked.connect(self.clear_display)
        self.percent_btn.clicked.connect(self.percentage_btn_get)
        
        
        
        self.equls_btn.clicked.connect(self.equls_fun_get)
        
        


# get numbers in lambda
        self.num7_btn.clicked.connect(lambda:self.press_it("7"))
        self.num4_btn.clicked.connect(lambda:self.press_it("4"))
        self.num1_btn.clicked.connect(lambda:self.press_it("1"))
        self.num00_btn.clicked.connect(lambda:self.press_it("0"))
        self.num8_btn.clicked.connect(lambda:self.press_it("8"))
        self.num5_btn.clicked.connect(lambda:self.press_it("5"))
        self.num2_btn.clicked.connect(lambda:self.press_it("2"))
        self.num000_btn.clicked.connect(lambda:self.press_it("00"))
        self.num9_btn.clicked.connect(lambda:self.press_it("9"))
        self.num6_btn.clicked.connect(lambda:self.press_it("6"))
        self.num3_btn.clicked.connect(lambda:self.press_it("3"))
        self.dot_btn.clicked.connect(lambda:self.press_it("."))
        # self.percent_btn.clicked.connect(lambda:self.press_it("%"))
        # self.multiply_btn.clicked.connect(lambda:self.press_it("x"))
        # self.plus_btn.clicked.connect(lambda:self.press_it("+"))
        # self.minus_btn.clicked.connect(lambda:self.press_it("-"))
        # self.division_btn.clicked.connect(lambda:self.press_it("÷"))
        # self.delete_btn.clicked.connect(lambda:self.press_it("Del"))
        # self.clear_btn.clicked.connect(lambda:self.press_it("c"))
        # self.equls_btn.clicked.connect(lambda:self.press_it("="))
        # self.label_display.setText("0")
        
        
    
    
        
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Calculator"))
        self.label_display.setText(_translate("Dialog", ""))
        # self.num7_btn.setText(_translate("Dialog", "7"))
        self.num7_btn.setText(_translate("Dialog","7"))
        
        
        
        
        # correct the top
        # use lambda
        
        
        
        
        
        self.num4_btn.setText(_translate("Dialog", "4"))
        self.num1_btn.setText(_translate("Dialog", "1"))
        self.num00_btn.setText(_translate("Dialog", "0"))
        self.num8_btn.setText(_translate("Dialog", "8"))
        self.num5_btn.setText(_translate("Dialog", "5"))
        self.num2_btn.setText(_translate("Dialog", "2"))
        self.num000_btn.setText(_translate("Dialog", "00"))
        self.num9_btn.setText(_translate("Dialog", "9"))
        self.num6_btn.setText(_translate("Dialog", "6"))
        self.num3_btn.setText(_translate("Dialog", "3"))
        self.dot_btn.setText(_translate("Dialog", "."))
        self.percent_btn.setText(_translate("Dialog", "%"))
        self.multiply_btn.setText(_translate("Dialog", "x"))
        self.plus_btn.setText(_translate("Dialog", "+"))
        self.minus_btn.setText(_translate("Dialog", "-"))
        self.division_btn.setText(_translate("Dialog", "÷ "))
        self.delete_btn.setText(_translate("Dialog", "Del"))
        self.clear_btn.setText(_translate("Dialog", "c"))
        self.equls_btn.setText(_translate("Dialog", "="))

    def press_it(self,number):
        if self.label_display.text()=="😂" + "delete me now":
            self.clear_display()
        # get the current value
        current = self.label_display.text()
        
        # if the current value is 0
        if current == "0":
            self.label_display.setText(number)
        else:
            
            self.label_display.setText(str(current) + str(number))


    def delete_btn_get(self):
        current=self.label_display.text()
        current=current[:-1]
        self.label_display.setText(current)
        
    # plus
    def plus_btn_get(self):
        if self.label_display.text()=="":
            return self.label_display.setText("0")
        get_number=self.label_display.text()
        global f_num 
        global math
        math="addition"
        f_num=float(get_number)
        self.clear_display()
        
    def minus_btn_get(self):
        if self.label_display.text()=="":
            return self.label_display.setText("0")
        get_number=self.label_display.text()
        global f_num 
        global math
        math="minus"
        f_num=float(get_number)
        self.clear_display()
        

    def division_btn_get(self):
        if self.label_display.text()=="":
            return self.label_display.setText("0")
       
        get_number=self.label_display.text() 
        global f_num 
        global math
        math="division"
        f_num=float(get_number)
        self.clear_display()
        

    def multiply_btn_get(self):
        if self.label_display.text()=="":
            return self.label_display.setText("0")
        get_number=self.label_display.text() 
        global f_num 
        global math
        math="multiplication"
        f_num=float(get_number)
        self.clear_display()
        
    def percentage_btn_get(self):
        self.clear_display()
        return self.label_display.setText("😂" + "delete me now")
      

    def equls_fun_get(self):
        
        second_number=float(self.label_display.text())
        if math=="addition":
          
         
            self.label_display.setText(str(f_num + second_number))
            
        if math=="minus":
            self.clear_display()
      
            # total=str(f_num - second_number)
            self.label_display.setText(str(f_num - second_number))
            
        if math=="division":
            self.clear_display()
          
            # total=str(f_num - second_number)
            self.label_display.setText(str(f_num / second_number))
            
        if math=="multiplication":
            self.clear_display()
          
            # total=str(f_num - second_number)
            self.label_display.setText(str(f_num * second_number))
            
        if math == "percentage":
            
          self.clear_display()
       
          result = f_num * (second_number / 100)
          self.label_display.setText(str(result))
            
            
            
            
            
            
            
            
            
        
        
        
    def clear_display(self):
        self.label_display.clear()
       
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
