# Form implementation generated from reading ui file 'csvpages.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QTableWidget, QTableWidgetItem, QHeaderView, QAbstractItemView, QMessageBox,QWidget,QFileDialog
from PyQt6.QtGui import QFont,QIcon
from PyQt6.QtCore import Qt, QSize, QRect, QPoint, QEvent
from connection import databasename
import sqlite3
import csv
# import pandas as pd


class Ui_Dialog(QWidget):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(403, 161)
        Dialog.setMinimumSize(QtCore.QSize(403, 161))
        # page title
        Dialog.setWindowTitle("CSV Pages")
        
        # logo
        Dialog.setWindowIcon(QIcon("logo/logo.jpeg"))
        
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(-1, -1, 401, 301))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, 9, 401, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.import_csv_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.import_csv_btn.setObjectName("import_csv_btn")
        self.horizontalLayout.addWidget(self.import_csv_btn)
        self.export_csv_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.export_csv_btn.setObjectName("export_csv_btn")
        self.horizontalLayout.addWidget(self.export_csv_btn)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 50, 401, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.daliy_total_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.daliy_total_btn.setObjectName("daliy_total_btn")
        self.horizontalLayout_2.addWidget(self.daliy_total_btn)
        self.item_total_bought_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.item_total_bought_btn.setObjectName("item_total_bought_btn")
        self.horizontalLayout_2.addWidget(self.item_total_bought_btn)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=self.frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 90, 401, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.total_sales_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.total_sales_btn.setObjectName("total_sales_btn")
        self.horizontalLayout_3.addWidget(self.total_sales_btn)
        self.total_price_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.total_price_btn.setObjectName("total_price_btn")
        self.horizontalLayout_3.addWidget(self.total_price_btn)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(parent=self.frame)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 130, 401, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.total_cus_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.total_cus_btn.setObjectName("total_cus_btn")
        self.horizontalLayout_4.addWidget(self.total_cus_btn)
        self.total_items_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.total_items_btn.setObjectName("total_items_btn")
        self.horizontalLayout_4.addWidget(self.total_items_btn)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        # styling btn
        self.import_csv_btn.setStyleSheet("background-color: #00a6ff; color: white; font-size: 14px; border-radius: 5px;")
        self.export_csv_btn.setStyleSheet("background-color: #00a6ff; color: white; font-size: 14px; border-radius: 5px;")
        self.daliy_total_btn.setStyleSheet("background-color: #00a6ff; color: white; font-size: 14px; border-radius: 5px;")
        self.item_total_bought_btn.setStyleSheet("background-color: #00a6ff; color: white; font-size: 14px; border-radius: 5px;")
        self.total_sales_btn.setStyleSheet("background-color: #00a6ff; color: white; font-size: 14px; border-radius: 5px;")
        self.total_price_btn.setStyleSheet("background-color: #00a6ff; color: white; font-size: 14px; border-radius: 5px;")
        self.total_cus_btn.setStyleSheet("background-color: #00a6ff; color: white; font-size: 14px; border-radius: 5px;")
        self.total_items_btn.setStyleSheet("background-color: #00a6ff; color: white; font-size: 14px; border-radius: 5px;")
        
        
        
        self.import_csv_btn.clicked.connect(self.open_file)
        self.export_csv_btn.clicked.connect(self.export_data)
        self.daily_total()
        self.item_total()
     
    
    
    def open_file(self):
        conn=sqlite3.connect(databasename)
        cur=conn.cursor()
        file_name, _ = QtWidgets.QFileDialog.getOpenFileName(None, "Open CSV", "", "CSV Files (*.csv)")
        if file_name:
            with open(file_name, 'r') as file:
                records=0
                for row in file:
                    if records==0:
                        records=1
                        continue
                    row=row.strip()
                    row=row.split(',')
                  
                    cur.execute("INSERT INTO items(name,category,price,bought_price,qty,qrcode,voltage) VALUES(?,?,?,?,?,?,?)",(row[0],row[1],row[2],row[3],row[4],row[5],row[6]))
                    conn.commit()
                    QMessageBox.information(self, "Success", "CSV Imported")
                    
                
        else:
            return
          
 
    
    def export_data(self):
        conn = sqlite3.connect(databasename)
        cur = conn.cursor()
        cur.execute("SELECT * FROM items")
        rows = cur.fetchall()
        conn.close()

        # Prompt the user to choose the directory
        file_path, _ = QFileDialog.getSaveFileName(self, 'Save CSV File', '', 'CSV Files (*.csv)')
        if not file_path:  # If the user cancels the dialog
            return

        # Save the data to the chosen file path
        with open(file_path, 'w', newline='') as file:
            writer = csv.writer(file)
            writer.writerow(['id', 'name', 'category', 'price', 'bought_price', 'qty', 'qrcode', 'voltage', 'created_at'])
            writer.writerows(rows)
        
        QMessageBox.information(self, "Success", "CSV Exported")
        
       
        
    def daily_total(self):
       conn = sqlite3.connect(databasename)
       cur = conn.cursor()
       cur.execute("SELECT SUM(total_price) FROM sales WHERE order_status='completed'")
       total = cur.fetchone()[0]
       conn.close()
       self.daliy_total_btn.setText(f"Daily Total: {total}")
       
       
       
       
    def item_total(self):
        conn = sqlite3.connect(databasename)
        cur = conn.cursor()
        cur.execute("SELECT SUM(price) FROM items")
        total = cur.fetchone()[0]
        conn.close()
        self.total_price_btn.setText(f"Total: {total}")
        
       

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "CSV"))
        self.import_csv_btn.setText(_translate("Dialog", "Import CSV"))
        self.export_csv_btn.setText(_translate("Dialog", "Export CSV"))
        self.daliy_total_btn.setText(_translate("Dialog", "Daliy Total"))
        self.item_total_bought_btn.setText(_translate("Dialog", "Total Bought"))
        self.total_sales_btn.setText(_translate("Dialog", "Total sales"))
        self.total_price_btn.setText(_translate("Dialog", "Total price"))
        self.total_cus_btn.setText(_translate("Dialog", "Total Customers"))
        self.total_items_btn.setText(_translate("Dialog", "Total Itmes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())


