# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QTableWidget, QTableWidgetItem, QHeaderView, QAbstractItemView, QMessageBox,QWidget
from PyQt6.QtGui import QFont,QIcon
from PyQt6.QtCore import Qt, QSize, QRect, QPoint, QEvent

from Textslider import Slider, count, text,txt
import hashlib

from PyQt6.QtPrintSupport import QPrinter, QPrintDialog, QPrintPreviewDialog
from PyQt6.QtGui import QPainter
# MESSAGE
  

from connection import databasename
import sqlite3

class Ui_registerform(QWidget):
    def setupUi(self, registerform):
        registerform.setObjectName("registerform")
        registerform.resize(400, 300)
        registerform.setFixedSize(400, 300)
        self.closepage=registerform
        registerform.setWindowIcon(QIcon('logo/logo.jpeg'))
        registerform.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(registerform)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_email = QtWidgets.QLabel(parent=registerform)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_email.setFont(font)
        self.label_email.setObjectName("label_email")
        self.horizontalLayout_2.addWidget(self.label_email)
        self.lineEdit_email = QtWidgets.QLineEdit(parent=registerform)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_email.setFont(font)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.horizontalLayout_2.addWidget(self.lineEdit_email)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_password = QtWidgets.QLabel(parent=registerform)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.horizontalLayout_3.addWidget(self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(parent=registerform)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.horizontalLayout_3.addWidget(self.lineEdit_password)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.register_btn = QtWidgets.QPushButton(parent=registerform)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.register_btn.setFont(QFont("sanserif",18))
        self.register_btn.setStyleSheet("background-color: blue; color: white; font-size: 24px; border-radius: 5px;")
        self.register_btn.setObjectName("register_btn")
        self.horizontalLayout_5.addWidget(self.register_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.have_an_account_btn = QtWidgets.QPushButton(parent=registerform)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.have_an_account_btn.setFont(font)
        self.have_an_account_btn.setObjectName("have_an_account_btn")
        self.horizontalLayout_6.addWidget(self.have_an_account_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_6)

        self.retranslateUi(registerform)
        QtCore.QMetaObject.connectSlotsByName(registerform)
        
        self.register_btn.clicked.connect(self.login)
        
        self.have_an_account_btn.clicked.connect(self.open_register)


   
    def login(self):
        email = self.lineEdit_email.text()
        password = self.lineEdit_password.text()
        password = hashlib.md5(password.encode())
        password = password.hexdigest()
        conn = sqlite3.connect(databasename)
        cur = conn.cursor()
        cur.execute("SELECT * FROM users WHERE email=? AND password=?", (email, password))
        user = cur.fetchone()
        conn.close()
        if user:
           
            QMessageBox.information(self, "Success", "Login successful")
            # Redirect to the dashboard
            self.open_salespage()
           
        else:
         
            QMessageBox.warning(self, "Error", "Invalid email or password")
        # Add your login logic here
        # You can use the email and password variables to authenticate the user
        # You can also use the database to retrieve the user's information
        # You can also use the database to store the user's information
        # You can also use the database to delete the user's information
        # You can also use the database to update the user's information
        # You can also use the database to retrieve the user's information
        
    
    def open_salespage(self):
            from sales import Ui_MainWindow
            self.salepage= QtWidgets.QMainWindow()
            self.salespage=Ui_MainWindow()
            self.salespage.setupUi(self.salepage)
            self.closepage.close()
            self.salepage.show()
            
            
    def open_register(self):
            from registeration import Ui_registerform
            self.register= QtWidgets.QWidget()
            self.registerpage=Ui_registerform()
            self.registerpage.setupUi(self.register)
            self.closepage.close()
            self.register.show()
        
    def retranslateUi(self, registerform):
        _translate = QtCore.QCoreApplication.translate
        registerform.setWindowTitle(_translate("registerform", "Login"))
        self.label_email.setText(_translate("registerform", "Email      "))
        self.label_password.setText(_translate("registerform", "Password"))
        self.register_btn.setText(_translate("registerform", "Login"))
        self.have_an_account_btn.setText(_translate("registerform", "Don\'t have an account? Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    registerform = QtWidgets.QWidget()
    ui = Ui_registerform()
    ui.setupUi(registerform)
    registerform.show()
    sys.exit(app.exec())
