# Form implementation generated from reading ui file 'registeration.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QTableWidget, QTableWidgetItem, QHeaderView, QAbstractItemView, QMessageBox,QWidget
from PyQt6.QtGui import QFont,QIcon
from PyQt6.QtCore import Qt, QSize, QRect, QPoint, QEvent

from Textslider import Slider, count, text,txt
import hashlib

# MESSAGE


from connection import databasename
import sqlite3

class Ui_registerform(QWidget):
    def setupUi(self, registerform):
        registerform.setObjectName("registerform")
        registerform.resize(400, 300)
        registerform.setWindowTitle("Register")
        self.closepage=registerform
        # remove title bar
        # registerform.setWindowFlags(Qt.WindowType.FramelessWindowHint)
        # registerform.setWindowFlags(Qt.WindowType.FramelessWindowHint)
        # registerform.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground)
        registerform.setStyleSheet("background-color: rgb(255, 255, 255);")
        # border radius
        
      
      
        
        # set fixed size
        registerform.setFixedSize(400, 300)
        registerform.setWindowIcon(QIcon('logo/logo.jpeg')) 
        self.verticalLayout = QtWidgets.QVBoxLayout(registerform)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_username = QtWidgets.QLabel(parent=registerform)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_username.setFont(font)
        self.label_username.setObjectName("label_username")
        self.horizontalLayout.addWidget(self.label_username)
        self.lineEdit_username = QtWidgets.QLineEdit(parent=registerform)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.horizontalLayout.addWidget(self.lineEdit_username)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_email = QtWidgets.QLabel(parent=registerform)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_email.setFont(font)
        self.label_email.setObjectName("label_email")
        self.horizontalLayout_2.addWidget(self.label_email)
        self.lineEdit_email = QtWidgets.QLineEdit(parent=registerform)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_email.setFont(font)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.horizontalLayout_2.addWidget(self.lineEdit_email)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_password = QtWidgets.QLabel(parent=registerform)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.horizontalLayout_3.addWidget(self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(parent=registerform)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.horizontalLayout_3.addWidget(self.lineEdit_password)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_position = QtWidgets.QLabel(parent=registerform)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_position.setFont(font)
        self.label_position.setObjectName("label_position")
        self.horizontalLayout_4.addWidget(self.label_position)
        self.lineEdit_position = QtWidgets.QLineEdit(parent=registerform)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_position.setFont(font)
        self.lineEdit_position.setObjectName("lineEdit_position")
        self.horizontalLayout_4.addWidget(self.lineEdit_position)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.register_btn = QtWidgets.QPushButton(parent=registerform)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.register_btn.setFont(QFont("sanserif",18))
        self.register_btn.setStyleSheet("QPushButton{\n"
"\n"
"background-color:blue;\n"
"color:white\n"
"}")
        self.register_btn.setObjectName("register_btn")
        self.horizontalLayout_5.addWidget(self.register_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.have_an_account_btn = QtWidgets.QPushButton(parent=registerform)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.have_an_account_btn.setFont(font)
        self.have_an_account_btn.setObjectName("have_an_account_btn")
        self.horizontalLayout_6.addWidget(self.have_an_account_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_6)

        self.retranslateUi(registerform)
        QtCore.QMetaObject.connectSlotsByName(registerform)
        self.lineEdit_position.hide()
        self.label_position.hide()
        
        
        self.register_btn.clicked.connect(self.create_register)
        self.have_an_account_btn.clicked.connect(self.loginscreen)



    def create_register(self):
        if self.lineEdit_email.text() == "" or self.lineEdit_password.text() == "" or self.lineEdit_username.text() == "":
            QMessageBox.warning(self, "Error", "Please fill in all fields.")
            return
        email = self.lineEdit_email.text()
        password = self.lineEdit_password.text()
        name = self.lineEdit_username.text()
        password = hashlib.md5(password.encode()).hexdigest()
      
        try:
            conn = sqlite3.connect(databasename)
            c = conn.cursor()
            c.execute("INSERT INTO users (email,password,name) VALUES (?,?,?)", (email, password,name))
            conn.commit()
            conn.close()
            QMessageBox.information(self, "Success", "Registration successful. You can now login.")
            self.loginscreen()
        except sqlite3.Error as e:
            QMessageBox.warning(self, "Error", "An error occurred while registering. Please try again.")
          
            conn.close()
        self.lineEdit_email.clear()
        self.lineEdit_password.clear()
        self.lineEdit_position.clear()
        self.lineEdit_username.clear()
        
    def loginscreen(self):
        from login import Ui_registerform
        self.login_window = QtWidgets.QWidget()
        self.ui = Ui_registerform()
        self.ui.setupUi(self.login_window)
        self.closepage.close()
        self.login_window.show()
       
        
    def retranslateUi(self, registerform):
        _translate = QtCore.QCoreApplication.translate
        registerform.setWindowTitle(_translate("registerform", "Registration Form"))
        self.label_username.setText(_translate("registerform", "User Name"))
        self.label_email.setText(_translate("registerform", "Email      "))
        self.label_password.setText(_translate("registerform", "Password"))
        self.label_position.setText(_translate("registerform", "Position"))
        self.register_btn.setText(_translate("registerform", "Register"))
        self.have_an_account_btn.setText(_translate("registerform", "Already have an account? Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    registerform = QtWidgets.QWidget()
    ui = Ui_registerform()
    ui.setupUi(registerform)
    registerform.show()
    sys.exit(app.exec())
